[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles==23.2.1",
    "fastapi>=0.118.0",
    "httpx>=0.28.1",
    "openai>=2.2.0",
    "python-dotenv==1.0.1",
    "uvicorn>=0.37.0",
]
